FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main

ARG DEBIAN_FRONTEND=noninteractive

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get update && apt-get install -y \
        binutils-aarch64-linux-gnu \
        build-essential \
        clang \
        cmake \
        gcc \
        git \
        libclang-dev \
        libpq-dev \
        lld \
        llvm \
        pkg-config \
        && apt-get clean
