FROM ubuntu:22.04

RUN apt-get update && \
    # https://askubuntu.com/a/1129284
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        binutils-aarch64-linux-gnu \
        build-essential \
        clang \
        cmake \
        gcc \
        git \
        libclang-dev \
        libpq5 \
        libpq-dev \
        lld \
        llvm \
        pkg-config \
        tzdata \
        && apt-get clean
