FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:main

RUN apt-get update && \
    apt-get install --assume-yes \
    binutils-aarch64-linux-gnu \
    build-essential \
    clang \
    cmake \
    gcc \
    git \
    libclang-dev \
    libpq-dev \
    lld \
    llvm \
    pkg-config
